base_url = "https://Li-zhienxuan.github.io/web_server"
title = "LilyXUAN"
description = "Lily & 哈基轩的空间"

# theme = "hermit"

build_search_index = true
compile_sass = true
highlight_code = true

# 分类系统定义
taxonomies = [
    { name = "tags", feed = true },
    { name = "categories", feed = true },
]

[extra]
# 作者信息
author = "LilyXUAN"
email = "Li.zhienxuan0516@gmail.com"  # 替换为你的邮箱
custom_css = ["css/global.css"]
since = 2024

# 强制 HTTPS 相关设置
force_https = true

# 社交链接
gitee= "li-zhienxuan_study"  # 替换为你的Gitee ID
github = "Li-zhienxuan"  # 替换为你的GitHub用户名
bilibili = "473911887"  # 替换为你的B站ID


# 页脚信息
footer_content = "© 2024-2025 LilyXUAN"

# 功能开关
copy_button = true
katex = true

# 导航菜单
[extra.nav]
links = [
    { url = "/posts", name = "记录" },
    { url = "/about", name = "关于" }
]

# 社交图标显示
[extra.social]
email = "Li.zhienxuan0516@gmail.com"  # 替换为你的邮箱
gitee= "li-zhienxuan_study"  # 替换为你的Gitee ID
github = "Li-zhienxuan"  # 替换为你的GitHub用户名
bilibili = "473911887"  # 替换为你的B站ID


# 代码高亮主题
highlight_theme = "obsidian"

[markdown]
highlight_code = true

